### ISSUE TITLE
error from pcbnew "rotation" is a list, not double

### ISSUE THREAD

**Issue by morrowwm** [mcbridejc/kicad_component_layout#2]
I have a new installation of KiCad Version: 6.0.4+dfsg-1~bpo11+1, release build, python3

Getting an error:
line 167, in Run
```
    167                 mod.SetOrientationDegrees(rotation)
TypeError: in method 'FOOTPRINT_SetOrientationDegrees', argument 2 of type 'double'
```
Changing line 166 from 
    166                 `rotation = props['rotation']`
to
    166                 `rotation = props['rotation'][0]`
gets the first element of the list into the rotation variable and the plugin works.

**Comment by mcbridejc** [comment]
Hi, 

The rotation field in the YAML should be a scalar, not a list. However, I see that my example in the README appears to make it a list, and that's misleading. I'll update the example. Thanks for pointing this out!

**Comment by morrowwm** [comment]
Ah, OK. I'm pretty new to YAML. Blindingly obvious now.
