### ISSUE TITLE
Please provide an example of the yaml generation script

### ISSUE THREAD

**Issue by morrowwm** [mcbridejc/kicad_component_layout#3]
Thanks for this script, it saves a ton of time and improves the accuracy of my layout.

Could you add an example of a script which generates the layout.yaml file? If you can't get to this soon, I'll build one and send it to you.

I'm currently building the text in a spreadsheet and copy-pasting it into the text file, which is tedious.

**Comment by mcbridejc** [comment]
What do you think an example should do? It's pretty application dependent how footprint coordinates are calculated, and I hope the YAML schema is straightforward enough. Also, many languages can be used to generate the YAML file, and there are lots of examples out there about how to write YAML (e.g. [this one]( https://www.w3schools.io/file/yaml-python-read-write/) for python) )

There is an example of generating `layout.yaml` in python in the `dmfwizard` project, [here](https://github.com/uwmisl/dmfwizard/blob/master/dmfwizard/kicad.py#L113) . 

I'm not opposed to adding an example or two of layout generation though if it's helpful. Perhaps a script to locate LEDs on a circle?

**Comment by jerseyp2** [comment]
A script example to locate LEDs on a circle (or ellipse) would be great. I'm running Kicad 6.99 nightlies, and I realize the script is not compatible at this point. Is there any way I can modify it so it will run? Thanks.

**Comment by mcbridejc** [comment]
I went ahead and added a quick LED locating example in the `examples` directory. 

@jerseyp2 The only issue I'm aware of with current nightlies is that until a few minutes ago when I merged PR #4, trying to place a part on the bottom (i.e. setting 'flip' to True) would cause an error about a missing argument 'aFlipLeftRight'; and actually that problem existed for all 6.x releases. 

I just tested the circle example with a recent nightly build and it worked.

**Comment by jerseyp2** [comment]
@mcbridejc Thanks! 

I ran the layout.py script and it created the correct layout.yaml in my 6.99 nightly. 

If I change the rotation: on D1 from 180.0 to 0.0 in the generated layout.yaml (I'm trying to both write and read LED positions), and then run the component_layout_plugin.py in pcbnew, I get an exception in the action plugin code on line 158: mod.SetPosition(pcbnew.wxPointMM(x0 + x, y0 + y)). I looked at the nightlies API and I don't think there is a VECTOR2I_MM. Should I log this as an issue?  Thanks again.

**Comment by mcbridejc** [comment]
@jerseyp2 That makes it seem like it is still using the wxPointMM instead of VECTOR2I_MM. For nightlies, you have to use VECTOR2I_MM. This makes me wonder, what is the version string for the pcbnew you are running? 

For me, it is `6.99.0-unknown-49bf717c0e~149~ubuntu21.10.1`

You can get this from the "About KiCad" dialog in pcbnew, or you can run `import pcbnew; pcbnew.GetBuildVersion()` in the "KiPython" scripting console.

**Comment by jerseyp2** [comment]
@mcbridejc Here is my Kicad version info:

Application: KiCad PCB Editor (64-bit)

Version: (6.99.0-2327-g56895db84c), release build

Libraries:
	wxWidgets 3.1.7
	FreeType 2.11.1
	HarfBuzz 4.2.0
	FontConfig 2.14.0
	libcurl/7.83.1-DEV Schannel zlib/1.2.12

Platform: Windows 10 (build 18363), 64-bit edition, 64 bit, Little endian, wxMSW

Build Info:
	Date: Jul  7 2022 07:22:34
	wxWidgets: 3.1.7 (wchar_t,wx containers)
	Boost: 1.79.0
	OCC: 7.6.0
	Curl: 7.83.1-DEV
	ngspice: 37
	Compiler: Visual C++ 1929 without C++ ABI

Build settings:
	KICAD_USE_OCC=ON
	KICAD_SPICE=ON

Github won't let me upload a screen shot for some reason, so here is the error message:
-------------------------------------------------------------------------------------------------
Traceback (most recent last call):
 
   File
   C:\Users/User/Documents/Kicad/6.99/scripting/plugins/component_layout_plugin.py, line
   158, in Run
      mod.SetPosition(pcbnew.wxPointMM(x0 + x, y0 +y))

  File "C:\Program Files\Kicad\6.99\Lib\site-packages\pcbnew.py, line 18929 in
  SetPosition 
   return _pcbnew.FOOTPRINT_SetPosition(self, aPos)

  TypeError: in method 'FOOTPRINT_SetPosition', argument 2 of type 'VECTOR2I const &'
-----------------------------------------------------------------------------------------------------
The code for SetPosition at line 18929 in pcbnew.py is:

  def SetPosition(self, aPos: "VECTOR2I") -> "void":
        r"""SetPosition(FOOTPRINT self, VECTOR2I aPos)"""
        return _pcbnew.FOOTPRINT_SetPosition(self, aPos)

I hope this helps.

Thanks.

**Comment by jerseyp2** [comment]
Sorry about the formatting. I'm new to Github and I should have checked.

**Comment by mcbridejc** [comment]
@jerseyp2 I see the problem then. Thanks for that. I opened a new issue and can push a fix soon.

**Comment by jerseyp2** [comment]
@mcbridejc In the led-circle example, the grid origin is set in layout.py, and written to layout.yaml. It works great. 

A suggestion for a possible enhancement would be to have layout.py read/write the grid origin from the kicad board. This would allow relative (to the origin) coordinates to be dumped to layout.yaml. In my case, I like to verify LED positioning sometimes by checking the xy location in the Kicad footprint properites dialog, where the positions are in relative coordinates. If these were the same coordinates as those in yaml.layout, it might give a certain comfort level when checking on positions.
